config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("", include("cores.urls", namespace="cores")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cores/urls.py
from django.urls import path
from rooms.views import HomeView

app_name = "cores"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.room_detail, name="detail"),
    path("search", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("change-password/", views.ChangePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
]

templates/partials/footer.html
<p class="hover:text-gray-800 all_ani ">Powered by Django</p>
<p class="hover:text-gray-800 all_ani">&copy; 2019 BENBNB, All rights reserved.</p>

templates/partials/nav.html
<ul class="flex items-center text-sm font-normal h-full">
{% if user.is_authenticated %}
  <li class="nav_animation nav_link hover:border-gray-700"><a class=" " href="{% url "users:profile" user.pk %}">PROFILE</a></li>
  <!-- ALSO CAN BE DONE BY : <a href="{{user.get_absolute_url}}">LOGOUT</a></li> -->
  <li class="nav_animation nav_link hover:border-gray-700"><a class=" " href="{% url "users:logout" %}">LOGOUT</a></li>
{% else %}
  <li class="nav_animation nav_link hover:border-gray-700"><a class="" href="{% url "users:login" %}">LOGIN</a></li>
  <li class="nav_animation nav_link hover:border-gray-700"><a class="" href="{% url "users:signup" %}">SIGN UP</a></li>
{% endif %}
</ul>

templates/partials/room_card.html
<div class="cursor-pointer w-1/2 xl:w-1/4 lg:w-1/4 md:w-1/2 sm:w-1/2 mb-8 px-2 table-cell">
  <div class="h-32 shadow-lg hover:shadow-xl search-box w-full lg:h-40 md:h-56 bg-cover rounded" style="background-image: url({{room.first_photo}});"><a href="{% url "rooms:detail" room.pk %}"></a></div>
  
  <div class="mt-2 flex w-11/12 overflow-hidden">
    {% if room.host.superhost %}
    <span class="mr-2 px-1 py-0 h-auto uppercase text-xs border border-gray-900 text-gray-900 rounded font-medium">
      superhost
    </span>
    {% endif %}
    <span class="text-sm font-light text-gray-700 block truncate">
      {{room.city}}, {{room.country.name}}
    </span>
  </div>
  <span class="flex text-sm flex items-center">
    <label class="mr-1" for="rate"><i class="fas fa-star text-xs text-red-500"></i></label>
    <p class="" id="rate">{{room.total_rating}}</p>
  </span>

  <span class="text-black text-xs lg:text-base md:text-base xl:text-base">{{room.name}}</span>
</div>

templates/partials/socialLogin.html
<div class="flex flex-col w-full">  
  <a class="btn-custom mb-3 text-white bg-gray-900 ani hover:bg-black" href="{% url "users:github-login" %}">
    Continue With Github
    <i class="ml-1 text-lg fab fa-github"></i>
  </a>
    
  <a class="btn-custom text-red-900 bg-yellow-400 ani hover:bg-yellow-500" href="{% url "users:kakao-login" %}">
    Continue With Kakao
    <i class="ml-1 text-lg text-red-900 far fa-comment"></i>
  </a>
</div>

<div class="flex text-center items-center w-full mt-8 ">
    <div class="mt-1 bg-gray-400 w-full h-px"></div>
    <span class="text- px-3 text-gray-500">or</span>
    <div class="mt-1 bg-gray-400 w-full h-px"></div>
  </div>

templates/partials/user_input.html
{{field}}
{% if field.errors %}
  {% for error in field.errors %}
    <div id="error_messages">
        <span>{{error}}</span>
    </div>
  {% endfor %}
{% endif %}