config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("", include("cores.urls", namespace="cores")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cores/urls.py
from django.urls import path
from rooms.views import HomeView

app_name = "cores"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.room_detail, name="detail"),
    path("search", views.SearchView.as_view(), name="search"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <title>{% block page_name %} {% endblock page_name %} | BENBNB</title>
  </head>
  <body class="text-gray-900 mt-32">
    <header class="inset-0 fixed bg-white px-6 border-b border-gray-300 container max-w-full h-20 flex items-center justify-between">
      <div class="flex-initial flex items-center w-9/12">
        <h1 class="text-xl"><a href="{% url "cores:home" %}">BENBNB</a></h1>
        <div>
          <img class="w-12" src="{% static "img/logo3.png" %}"></img>
        </div>
        {% block search-bar %}
          <form class="w-9/12" method="get" action="{% url "rooms:search" %}">
            <input class="w-8/12 bg-white search-box text-xs placeholder-gray-700 font-semibold rounded px-6 py-2 focus:outline-none hover:shadow-lg shadow-md" name="city" placeholder="Search by City"/>
          </form>
        {% endblock search-bar %}
      </div>
      {% include "partials/nav.html" %}
    </header>
    <main class="h-full px-4">
      {% include "messages.html" %}
      {% block content %}{% endblock %}
    </main>
    <footer class="container mx-auto text-center py-10 px-10 mt-10 py-3 border-t border-gray-300 text-sm text-gray-400">
        {% include "partials/footer.html" %}
    </footer>
  </body>
</html>

templates/messages.html
{% if messages %}
<ul class="justify-center flex items-center w-full messages">
  {% for message in messages %}
    <li {% if message.tags %} class="absolute z-10 w-64 text-center py-3 px-4 message {{ message.tags }}" {% endif %}>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}

templates/verification.html
<div style="
  background-color: #f8f8f8;
  padding:37px;
">
  <h1>Verify Email Here</h1>
  <a href="http://127.0.0.1:8000/users/verify/{{secret}}"
  style="
  cursor:pointer;
  text-decoration:none;
  
">
    <button style="
      background-color:#272121;
      color:#f6f6f6;
      border-radius:3px;
      border:none;
      text-align:center;
      font-size:12px;
      padding: 7px;
      cursor:pointer;
    ">CLICK ME</button>
    </a>
</div>