config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("", include("cores.urls", namespace="cores")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cores/urls.py
from django.urls import path
from rooms.views import HomeView

app_name = "cores"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("change-password/", views.ChangePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import uuid
from django.conf import settings
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.shortcuts import reverse
from django.template.loader import render_to_string


class User(AbstractUser):

    """ Custom User Model """

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHERS = "others"

    LANGUAGE_KOREAN = "kr"
    LANGUAGE_ENGLISH = "en"

    CURRENCY_KRW = "kr"
    CURRENCY_USD = "us"

    AUTH_EMAIL = "Email"
    AUTH_GITHUB = "Github"
    AUTH_KAKAO = "Kakao"

    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
        (GENDER_OTHERS, "Others"),
    )
    LANGUAGE_CHOICES = ((LANGUAGE_KOREAN, "Korean"), (LANGUAGE_ENGLISH, "English"))
    CURRENCY_CHOICES = ((CURRENCY_KRW, "KRW"), (CURRENCY_USD, "USD"))
    AUTH_CHOICES = (
        (AUTH_EMAIL, "Email"),
        (AUTH_GITHUB, "Github"),
        (AUTH_KAKAO, "Kakao"),
    )

    gender = models.CharField(choices=GENDER_CHOICES, max_length=10, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    language = models.CharField(
        max_length=2, choices=LANGUAGE_CHOICES, blank=True, default=LANGUAGE_ENGLISH
    )
    currency = models.CharField(
        max_length=2, choices=CURRENCY_CHOICES, blank=True, default=CURRENCY_USD
    )
    avatar = models.ImageField(upload_to="avatars", blank=True)
    bio = models.TextField(blank=True)
    superhost = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=120, default="", blank=True)
    auth = models.CharField(max_length=40, choices=AUTH_CHOICES, default=AUTH_EMAIL)

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    def verify_email(self):

        if self.email_verified is False:
            secret = uuid.uuid4().hex[:20]
            self.email_secret = secret

            SUBJECT = "Verify Email"
            FROM = settings.EMAIL_FROM
            TO_LIST = [self.email]
            HTML_MESSAGE = render_to_string("verification.html", {"secret": secret})
            MESSAGE = strip_tags(HTML_MESSAGE)
            send_mail(
                SUBJECT,
                MESSAGE,
                FROM,
                TO_LIST,
                fail_silently=False,
                html_message=HTML_MESSAGE,
            )
            self.save()
        return

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . import models


class LoginForms(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        try:
            user = models.User.objects.get(username=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Wrong password"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User doesn't exist"))


class SignUpForms(forms.ModelForm):
    """ Sign Up Forms Definition """

    class Meta:

        model = models.User
        fields = ("first_name", "last_name", "email")
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email"}),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password Confirmation"})
    )

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("Password doesn't match")
        else:
            return password

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            user = models.User.objects.get(username=email)
            if user is not None:
                raise forms.ValidationError("This email has been using by others")
        except models.User.DoesNotExist:
            return email

    def save(self, *args, **kwargs):

        # ModelForm saves object automatically, but doesn't care about that
        # username is email and creating password.
        # So in here, we are configuring it manually.
        user = super().save(commit=False)
        password = self.cleaned_data.get("password")
        email = self.cleaned_data.get("email")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
import os
import requests
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView, DetailView, UpdateView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.core.files.base import ContentFile
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from . import forms, models, mixins


class LoginView(mixins.LoggedOutOnlyView, View):
    """ Login View Definition """

    def get(self, request):

        form = forms.LoginForms()

        return render(request, "users/login.html", {"form": form})

    def post(self, request):

        form = forms.LoginForms(request.POST)

        if form.is_valid():

            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, f"Welcome back {user.first_name}")
                return redirect(reverse("cores:home"))

        return render(request, "users/login.html", {"form": form})


def log_out(request):

    logout(request)
    messages.info(request, f"See you later")
    return redirect(reverse("cores:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):
    """ Sign Up View Definition """

    template_name = "users/signup.html"
    form_class = forms.SignUpForms
    success_url = reverse_lazy("cores:home")

    def form_valid(self, form):

        form.save()  # If the form is valid, gonna save
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            user.verify_email()
            login(self.request, user)
        else:
            return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.save()
        # to do: add success message
    except models.User.DoesNotExist:
        # to do: add error message
        pass
    return redirect(reverse("cores:home"))


def github_login(request):
    client_id = os.environ.get("GITHUB_ID")
    redirect_uri = "http://127.0.0.1:8000/users/login/github/callback"
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
    )


class GithubException(Exception):
    """ Custom Exception """

    pass


def github_callback(request):
    try:
        client_id = os.environ.get("GITHUB_ID")
        client_secret = os.environ.get("GITHUB_SECRET")
        code = request.GET.get("code", None)
        if code is not None:
            post_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            post_request_error = post_request.json().get("error", None)
            if post_request_error is not None:
                raise GithubException()
            access_token = post_request.json().get("access_token")
            get_request = requests.get(
                "https://api.github.com/user",
                headers={
                    "Authorization": f"token {access_token}",
                    "Accept": "application/json",
                },
            )
            username = get_request.json().get("login")
            if username is not None:
                name = get_request.json().get("name")
                email = get_request.json().get("email")
                bio = get_request.json().get("bio")
                avatar_url = get_request.json().get("avatar_url")
                try:
                    user = models.User.objects.get(email=email)
                    if avatar_url is not None:
                        get_photo = requests.get(avatar_url)
                        content_photo = get_photo.content
                        user.avatar.save(f"{name}-avatar", ContentFile(content_photo))
                    if user.auth != models.User.AUTH_GITHUB:
                        raise GithubException(f"Try {user.auth} login method.")
                except models.User.DoesNotExist:
                    # Not Using 'create_user' because in here, we're not taking care of passwords
                    user = models.User.objects.create(
                        username=email,
                        first_name=name,
                        bio=bio,
                        email=email,
                        email_verified=True,
                        auth=models.User.AUTH_GITHUB,
                    )
                    if avatar_url is not None:
                        get_photo = requests.get(avatar_url)
                        content_photo = get_photo.content
                        user.avatar.save(f"{name}-avatar", ContentFile(content_photo))
                    user.set_unusable_password()
                    user.save()
                finally:
                    messages.success(request, f"Welcome back {user.first_name}")
                    login(request, user)
                    return redirect(reverse("cores:home"))
            else:
                raise GithubException("Cannot get User info")
        else:
            raise GithubException("Can not get a code from Github. Please try again. ")
    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


def kakao_login(request):
    app_key = os.environ.get("KAKAO_KEY")
    redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={app_key}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    """ Custom Exception """

    pass


def kakao_callback(request):
    try:
        code = request.GET.get("code", None)
        client_id = os.environ.get("KAKAO_KEY")
        redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
        get_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )
        json_token_result = get_request.json()
        access_token = json_token_result.get("access_token")
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        profile_request = profile_request.json()
        kakao_account = profile_request.get("kakao_account")
        email = kakao_account.get("email", None)
        gender = kakao_account.get("gender", None)
        nickname = kakao_account.get("profile").get("nickname", None)
        if email is None:
            raise KakaoException()
        try:
            user = models.User.objects.get(email=email)
            if user.auth != models.User.AUTH_KAKAO:  # If user has kakao auth
                raise KakaoException()

        except models.User.DoesNotExist:
            user = models.User.objects.create(
                username=email,
                first_name=nickname,
                email=email,
                gender=gender.lower(),
                email_verified=True,
                auth=models.User.AUTH_KAKAO,
            )
            user.set_unusable_password()
            user.save()
        login(request, user)  # We are gonna log the user in
        messages.success(request, f"Welcome back {user.first_name}")
        return redirect(reverse("cores:home"))
    except Exception:

        """
        requests.post(
            "https://kapi.kakao.com/v1/user/unlink",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        """
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):
    model = models.User
    context_object_name = "user_obj"
    # This(context_object_name) prevents replacing request.user and lets us stick with the current logged in user.

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rooms"] = self.object.rooms
        context["hello"] = "hello"
        return context


class UpdateProfileView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.User
    success_message = "Profile Updated"
    fields = (
        "first_name",
        "last_name",
        "email",
        "bio",
        "gender",
        "avatar",
        "date_of_birth",
        "language",
        "currency",
    )
    template_name = "users/update_profile.html"

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        self.object.username = email
        self.object.save()
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        fields_list = [
            "first_name",
            "last_name",
            "email",
            "bio",
            "gender",
            "avatar",
            "date_of_birth",
            "language",
            "currency",
        ]

        def set_placeholder(field_name, placeholder):
            form.fields[field_name].widget.attrs = {"placeholder": placeholder}

        for item in fields_list:
            item_name = item.replace("_", " ")
            item_name = item_name.capitalize()
            set_placeholder(item, item_name)

        return form


class ChangePasswordView(

templates/users/login.html
{% extends "base.html" %}

{% block page_name %} LOGIN {% endblock page_name %}

{% block search-bar %}{% endblock search-bar %}

{% block content %}
  <div class="lg:w-1/3 md:w-11/12 p-6 border border-gray-300 container mx-auto flex flex-col items-center">
    {% include "partials/socialLogin.html" %}
    <form class="w-full mt-10 flex flex-col items-center" method="post" action="{% url "users:login" %}">
      {% csrf_token %}
      {{form.email}}
      {% if form.email.errors %}
        {% for error in form.email.errors %}
        <div id="error_messages">
            <span>{{error}}</span>
        </div>
        {% endfor %}
      {% endif %}
      {{form.password}}
      {% if form.password.errors %}
        {% for error in form.password.errors %}
        <div id="error_messages">
            <span>{{error}}</span>
        </div>
        {% endfor %}
      {% endif %}
      <button class="ani hover:bg-red-700 text-center mb-3 btn-custom text-white bg-red-500">Login</button>
    </form>
  </div>
{% endblock %}

templates/users/signup.html
{% extends "base.html" %}

{% block page_name %} SIGN UP {% endblock page_name %}

{% block search-bar %}{% endblock search-bar %}

{% block content %}
  <div class="xl:w-1/3 lg:w-1/3 w-11/12 container mx-auto border p-6 border border-gray-300 flex flex-col items-center">
    {% include "partials/socialLogin.html" %}
    <form class="flex flex-col items-center w-full mt-10" method="POST" action="{% url "users:signup" %}">
      {% csrf_token %}

      {{form.first_name}}
      {% if form.first_name.errors %}
        {% for error in form.first_name.errors %}
        <div id="error_messages">
            <span>{{error}}</span>
        </div>
        {% endfor %}
      {% endif %}

      {{form.last_name}}
      {% if form.last_name.errors %}
        {% for error in form.last_name.errors %}
        <div id="error_messages">
            <span>{{error}}</span>
        </div>
        {% endfor %}
      {% endif %}

      {{form.email}}
      {% if form.email.errors %}
        {% for error in form.email.errors %}
        <div id="error_messages">
            <span>{{error}}</span>
        </div>
        {% endfor %}
      {% endif %}

      {{form.password}}
      {% if form.password.errors %}
        {% for error in form.password.errors %}
        <div id="error_messages">
            <span>{{error}}</span>
        </div>
        {% endfor %}
      {% endif %}

      {{form.password1}}
      {% if form.password1.errors %}
        {% for error in form.password1.errors %}
        <div id="error_messages">
            <span>{{error}}</span>
        </div>
        {% endfor %}
      {% endif %}
      <button class="ani hover:bg-red-700 text-center mb-3 btn-custom text-white bg-red-500">Sign Up</button>
    </form>
  </div>
{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}

{% block page_name %} UPDATE {% endblock page_name %}

{% block search-bar %}{% endblock search-bar %}

{% block content %}
  <div class="lg:w-1/3 md:w-11/12 p-6 border border-gray-300 container mx-auto flex flex-col items-center">
    <form class="w-full mt-10 flex flex-col" method="post" action="{% url "users:update" %}" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
        {% include "partials/user_input.html" with field=field %}
      {% endfor %}
      <button class="ani hover:bg-red-700 text-center mb-3 btn-custom text-white bg-red-500">Update</button>
    </form>
  </div>
{% endblock %}

templates/users/user_detail.html
{% extends "base.html" %} 
{% load static %}

{% block page_name %} {{user.first_name}} {%endblock page_name %} 

{% block content %}
<div class="p-4 w-full flex justify-center items-center mb-6">
  <div class="w-2/5 rounded-sm border shadow-md flex flex-col items-center w-auto py-6 px-10">
    {% include "mixins/profile.html" with user=user_obj %}
    <span class="mb-8 font-light text-3xl">{{user_obj.first_name}}</span>
    <span class="mb-3">{{user_obj.bio}}</span>
    <span class="mb-3">{{user_obj.email}}</span>
    {% if user == user_obj %}
      <a href="{% url "users:update" %}" class="px-6 py-1 btn bg-gray-600 rounded text-gray-300 hover:text-white all_ani hover:bg-gray-800 ">Edit Profile</a>
      <a href="{%  url "users:password" %}" class="text-teal-400 hover:text-teal-500 all_ani">Change Password</a>
    {% endif %}
  </div>
</div>
<div class="flex flex-col items-center justify-center">
  {% if user_obj.room.count > 0 %}
  <div class="flex flex-wrap lg:w-11/12 md:w-4/5 sm:w-2/3">
    {% if rooms %}
    <span class="w-full text-center text-2xl font-light mb-6">{{user_obj.first_name}}'s Rooms</span>
      {% for room in rooms.all %}
        {% include "partials/room_card.html" with room=room %}
      {% endfor %}
    {% endif %}
  </div>
  {% endif %}
</div>
{% endblock %}